/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg_iv.h"

bool_t
xdr_retorno (XDR *xdrs, retorno *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_ret))
		 return FALSE;
	switch (objp->cod_ret) {
	case 1:
		 if (!xdr_vector (xdrs, (char *)objp->retorno_u.message, 800,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
