/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_IV_H_RPCGEN
#define _MSG_IV_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct retorno {
	int cod_ret;
	union {
		char message[800];
	} retorno_u;
};
typedef struct retorno retorno;

#define MESSAGEPROG 0x20000099
#define MESSAGEVERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTMESSAGE 1
extern  retorno * printmessage_2(char **, CLIENT *);
extern  retorno * printmessage_2_svc(char **, struct svc_req *);
extern int messageprog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTMESSAGE 1
extern  retorno * printmessage_2();
extern  retorno * printmessage_2_svc();
extern int messageprog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_retorno (XDR *, retorno*);

#else /* K&R C */
extern bool_t xdr_retorno ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_IV_H_RPCGEN */
