/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg_iv.h"

retorno *
printmessage_2_svc(char **argp, struct svc_req *rqstp)
{
	static retorno  result;

	/*
	 * insert server code here
	 */

	return &result;
}
