/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "numerador.h"


void devolverVendedor(char *host, int numero)
{
	CLIENT *clnt;

	void  *result_4;
	int  devolvervendedor_2_arg;

	devolvervendedor_2_arg = numero;

#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_4 = devolvervendedor_2(&devolvervendedor_2_arg, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
