/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "numerador.h"

bool_t
xdr_RetornoCliente (XDR *xdrs, RetornoCliente *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->idCliente))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idVendedorLibre))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_retornoCliente (XDR *xdrs, retornoCliente *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_ret))
		 return FALSE;
	switch (objp->cod_ret) {
	case 1:
		 if (!xdr_RetornoCliente (xdrs, &objp->retornoCliente_u.retorno))
			 return FALSE;
		break;
	case 2:
		 if (!xdr_vector (xdrs, (char *)objp->retornoCliente_u.informacion, 800,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_retornoVendedor (XDR *xdrs, retornoVendedor *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_ret))
		 return FALSE;
	switch (objp->cod_ret) {
	case 1:
		 if (!xdr_int (xdrs, &objp->retornoVendedor_u.idVendedor))
			 return FALSE;
		break;
	case 2:
		 if (!xdr_vector (xdrs, (char *)objp->retornoVendedor_u.informacion, 800,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
