/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "numerador.h"


void devolverCliente(char *host, int numero)
{
	CLIENT *clnt;

	void  *result_3;
	int devolvercliente_2_arg;

	devolvercliente_2_arg = numero;
	
#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_3 = devolvercliente_2(&devolvercliente_2_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
