/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "numerador.h"


int numerarVendedor(char *host)
{

	CLIENT *clnt;
	retorno  *result_2;
	char *numeradorvendedor_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_2 = numeradorvendedor_2((void*)&numeradorvendedor_2_arg, clnt);
	if (result_2 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */


	return (*result_2).retorno_u.numero;
}

