/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NUMERADOR_H_RPCGEN
#define _NUMERADOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct retorno {
	int cod_ret;
	union {
		int numero;
		char informacion[800];
	} retorno_u;
};
typedef struct retorno retorno;

#define NUMERADOR 0x20000099
#define NUMERADOR2 2

#if defined(__STDC__) || defined(__cplusplus)
#define NUMERADORCLIENTE 1
extern  retorno * numeradorcliente_2(void *, CLIENT *);
extern  retorno * numeradorcliente_2_svc(void *, struct svc_req *);
#define NUMERADORVENDEDOR 2
extern  retorno * numeradorvendedor_2(void *, CLIENT *);
extern  retorno * numeradorvendedor_2_svc(void *, struct svc_req *);
#define DEVOLVERCLIENTE 3
extern  void * devolvercliente_2(int *, CLIENT *);
extern  void * devolvercliente_2_svc(int *, struct svc_req *);
#define DEVOLVERVENDEDOR 4
extern  void * devolvervendedor_2(int *, CLIENT *);
extern  void * devolvervendedor_2_svc(int *, struct svc_req *);
#define RESETEARCLIENTES 5
extern  void * resetearclientes_2(void *, CLIENT *);
extern  void * resetearclientes_2_svc(void *, struct svc_req *);
#define RESETEARVENDEDORES 6
extern  void * resetearvendedores_2(void *, CLIENT *);
extern  void * resetearvendedores_2_svc(void *, struct svc_req *);
#define LISTADOCLIENTES 7
extern  retorno * listadoclientes_2(void *, CLIENT *);
extern  retorno * listadoclientes_2_svc(void *, struct svc_req *);
#define LISTADOVENDEDORES 8
extern  retorno * listadovendedores_2(void *, CLIENT *);
extern  retorno * listadovendedores_2_svc(void *, struct svc_req *);
extern int numerador_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define NUMERADORCLIENTE 1
extern  retorno * numeradorcliente_2();
extern  retorno * numeradorcliente_2_svc();
#define NUMERADORVENDEDOR 2
extern  retorno * numeradorvendedor_2();
extern  retorno * numeradorvendedor_2_svc();
#define DEVOLVERCLIENTE 3
extern  void * devolvercliente_2();
extern  void * devolvercliente_2_svc();
#define DEVOLVERVENDEDOR 4
extern  void * devolvervendedor_2();
extern  void * devolvervendedor_2_svc();
#define RESETEARCLIENTES 5
extern  void * resetearclientes_2();
extern  void * resetearclientes_2_svc();
#define RESETEARVENDEDORES 6
extern  void * resetearvendedores_2();
extern  void * resetearvendedores_2_svc();
#define LISTADOCLIENTES 7
extern  retorno * listadoclientes_2();
extern  retorno * listadoclientes_2_svc();
#define LISTADOVENDEDORES 8
extern  retorno * listadovendedores_2();
extern  retorno * listadovendedores_2_svc();
extern int numerador_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_retorno (XDR *, retorno*);

#else /* K&R C */
extern bool_t xdr_retorno ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NUMERADOR_H_RPCGEN */
