/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "numerador.h"

#include "commonNumerador.h"

/* Funciones RPC dispoibles */

int numerarCliente(char *host);
int numerarVendedor(char *host);
void devolverCliente(char *host, int numero);
void devolverVendedor(char *host, int numero);

void resetearClientes(char *host);
void resetearVendedores (char *host);
void obtenerListadoClientes(char *host, char *listado);
void obtenerListadoVendedores(char *host, char *listado);

int numerarCliente(char *host)
{
	CLIENT *clnt;
	retorno  *result_1;
	char *numeradorcliente_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = numeradorcliente_2((void*)&numeradorcliente_2_arg, clnt);
	if (result_1 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	return (*result_1).retorno_u.numero;
}

int numerarVendedor(char *host)
{

	CLIENT *clnt;
	retorno  *result_2;
	char *numeradorvendedor_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_2 = numeradorvendedor_2((void*)&numeradorvendedor_2_arg, clnt);
	if (result_2 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */


	return (*result_2).retorno_u.numero;
}

void devolverCliente(char *host, int numero)
{
	CLIENT *clnt;

	void  *result_3;
	int devolvercliente_2_arg;

	devolvercliente_2_arg = numero;
	
#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_3 = devolvercliente_2(&devolvercliente_2_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void devolverVendedor(char *host, int numero)
{
	CLIENT *clnt;

	void  *result_4;
	int  devolvervendedor_2_arg;

	devolvervendedor_2_arg = numero;

#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_4 = devolvervendedor_2(&devolvervendedor_2_arg, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void resetearClientes(char *host)
{
	CLIENT *clnt;
	
	void  *result_5;
	char *resetearclientes_2_arg;
	
#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	
	result_5 = resetearclientes_2((void*)&resetearclientes_2_arg, clnt);
	if (result_5 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void resetearVendedores (char *host)
{
	CLIENT *clnt;
	
	void  *result_6;
	char *resetearvendedores_2_arg;
	
#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_6 = resetearvendedores_2((void*)&resetearvendedores_2_arg, clnt);
	if (result_6 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void obtenerListadoClientes(char *host, char *listado)
{
	CLIENT *clnt;

	retorno  *result_7;
	char *listadoclientes_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_7 = listadoclientes_2((void*)&listadoclientes_2_arg, clnt);
	if (result_7 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	memcpy(listado,(*result_7).retorno_u.informacion, MAX_CLIENTES);
	
}

void obtenerListadoVendedores(char *host, char *listado)
{
	CLIENT *clnt;

	retorno  *result_8;
	char *listadovendedores_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, NUMERADOR, NUMERADOR2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_8 = listadovendedores_2((void*)&listadovendedores_2_arg, clnt);
	if (result_8 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	memcpy(listado, (*result_8).retorno_u.informacion, MAX_VENDEDORES); 
}
