/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NUMERADOR_H_RPCGEN
#define _NUMERADOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct RetornoCliente {
	int idCliente;
	int idVendedorLibre;
};
typedef struct RetornoCliente RetornoCliente;

struct retornoCliente {
	int cod_ret;
	union {
		struct RetornoCliente retorno;
		char informacion[800];
	} retornoCliente_u;
};
typedef struct retornoCliente retornoCliente;

struct retornoVendedor {
	int cod_ret;
	union {
		int idVendedor;
		char informacion[800];
	} retornoVendedor_u;
};
typedef struct retornoVendedor retornoVendedor;

#define NUMERADORCLIENTE 0x20000099
#define NUMERADORCLIENTE1 1

#if defined(__STDC__) || defined(__cplusplus)
#define OBTENERIDCLIENTE 1
extern  retornoCliente * obteneridcliente_1(void *, CLIENT *);
extern  retornoCliente * obteneridcliente_1_svc(void *, struct svc_req *);
#define DEVOLVERIDCLIENTE 2
extern  void * devolveridcliente_1(int *, CLIENT *);
extern  void * devolveridcliente_1_svc(int *, struct svc_req *);
#define RESETEARCLIENTES 3
extern  void * resetearclientes_1(void *, CLIENT *);
extern  void * resetearclientes_1_svc(void *, struct svc_req *);
#define LISTADOCLIENTES 4
extern  retornoCliente * listadoclientes_1(void *, CLIENT *);
extern  retornoCliente * listadoclientes_1_svc(void *, struct svc_req *);
extern int numeradorcliente_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OBTENERIDCLIENTE 1
extern  retornoCliente * obteneridcliente_1();
extern  retornoCliente * obteneridcliente_1_svc();
#define DEVOLVERIDCLIENTE 2
extern  void * devolveridcliente_1();
extern  void * devolveridcliente_1_svc();
#define RESETEARCLIENTES 3
extern  void * resetearclientes_1();
extern  void * resetearclientes_1_svc();
#define LISTADOCLIENTES 4
extern  retornoCliente * listadoclientes_1();
extern  retornoCliente * listadoclientes_1_svc();
extern int numeradorcliente_1_freeresult ();
#endif /* K&R C */

#define NUMERADORVENDEDOR 0x2000009A
#define NUMERADORVENDEDOR1 1

#if defined(__STDC__) || defined(__cplusplus)
#define OBTENERIDVENDEDOR 1
extern  retornoVendedor * obteneridvendedor_1(void *, CLIENT *);
extern  retornoVendedor * obteneridvendedor_1_svc(void *, struct svc_req *);
#define VENDEDORLIBRE 2
extern  void * vendedorlibre_1(int *, CLIENT *);
extern  void * vendedorlibre_1_svc(int *, struct svc_req *);
#define DEVOLVERIDVENDEDOR 3
extern  void * devolveridvendedor_1(int *, CLIENT *);
extern  void * devolveridvendedor_1_svc(int *, struct svc_req *);
#define RESETEARVENDEDORES 4
extern  void * resetearvendedores_1(void *, CLIENT *);
extern  void * resetearvendedores_1_svc(void *, struct svc_req *);
#define LISTADOVENDEDORES 5
extern  retornoVendedor * listadovendedores_1(void *, CLIENT *);
extern  retornoVendedor * listadovendedores_1_svc(void *, struct svc_req *);
extern int numeradorvendedor_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OBTENERIDVENDEDOR 1
extern  retornoVendedor * obteneridvendedor_1();
extern  retornoVendedor * obteneridvendedor_1_svc();
#define VENDEDORLIBRE 2
extern  void * vendedorlibre_1();
extern  void * vendedorlibre_1_svc();
#define DEVOLVERIDVENDEDOR 3
extern  void * devolveridvendedor_1();
extern  void * devolveridvendedor_1_svc();
#define RESETEARVENDEDORES 4
extern  void * resetearvendedores_1();
extern  void * resetearvendedores_1_svc();
#define LISTADOVENDEDORES 5
extern  retornoVendedor * listadovendedores_1();
extern  retornoVendedor * listadovendedores_1_svc();
extern int numeradorvendedor_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_RetornoCliente (XDR *, RetornoCliente*);
extern  bool_t xdr_retornoCliente (XDR *, retornoCliente*);
extern  bool_t xdr_retornoVendedor (XDR *, retornoVendedor*);

#else /* K&R C */
extern bool_t xdr_RetornoCliente ();
extern bool_t xdr_retornoCliente ();
extern bool_t xdr_retornoVendedor ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NUMERADOR_H_RPCGEN */
