/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "numerador.h"

#include "numerador.h"
#include "commonNumerador.h"

struct RetornoCliente numerarCliente(char *host);
void devolverCliente(char *host, int numero);
void resetearClientes(char *host);
void obtenerListadoClientes(char *host, EstadoClientes *listado);

int numerarVendedor(char *host);
void liberarVendedor(char *host, int numero);
void devolverVendedor(char *host, int numero);
void resetearVendedores(char *host);
void obtenerListadoVendedores(char *host, EstadoVendedores *listado);

void manejarClientes(char *host) {
    struct RetornoCliente retorno;
    EstadoClientes clientes[MAX_CLIENTES];
    int cliente;
    char c;
    int i;
    
    printf("Ingrese una opcion:\n\tc - ObtenerCliente\n\td - DevolverCliente\n\tr - Resetear Clientes\n\tl - Listar Clientes\n");
    
    scanf("%c", &c);

    printf("Opcion elegida: %c\n", c);
    switch (c) {
        case 'c':
            retorno = numerarCliente(host);
            printf("Cliente obtenido: %d con vendedor %d.\n", retorno.idCliente, retorno.idVendedorLibre);
            break;
        case 'd':
            printf("Ingrese el cliente a devolver.\n");
            scanf("%d", &cliente);
            devolverCliente(host, cliente);
            break;
        case 'r':
            printf("Reseteando clientes.\n");
            resetearClientes(host);
            break;
        case 'l':
            printf("Listando Clientes.\n");           
            obtenerListadoClientes(host, clientes);
            for (i = 0; i < MAX_CLIENTES; ++i) printf("Cliente %d: %d\n", i + 1, clientes[i]);
            break;
        default:
            printf("Error, los valores posibles son:\n\tc - ObtenerCliente\n\td - DevolverCliente\n\tr - Resetear Clientes\n\tl - Listar Clientes\n");
            break;
    }
}

void manejarVendedores(char *host) {
    EstadoVendedores vendedores[MAX_VENDEDORES];
    int vendedor;
    char c;
    int i;

    printf("Ingrese una opcion:\n\tv - Obtener Vendedor\n\tl - Liberar Vendedor\n\td - Devolver Vendedor\n\tr - Resetear Vendedores\n\tx - Listar Vendedores\n");
    scanf("%c", &c);

    printf("Opcion elegida: %c\n", c);
    switch (c) {
        case 'v':
            vendedor = numerarVendedor(host);
            printf("Vendedor obtenido: %d.\n",vendedor);
            break;
        case 'l':
            printf("Ingrese el vendedor a liberar.\n");
            scanf("%d", &vendedor);
            liberarVendedor(host, vendedor);
            break;
        case 'd':
            printf("Ingrese el vendedor a devolver.\n");
            scanf("%d", &vendedor);
            devolverVendedor(host, vendedor);
            break;
        case 'r':
            printf("Reseteando vendedores.\n");
            resetearVendedores(host);
            break;
        case 'x':
            printf("Listando Vendedores.\n");           
            obtenerListadoVendedores(host, vendedores);
            for (i = 0; i < MAX_VENDEDORES; ++i) printf("Cliente %d: %d\n", i + 1, vendedores[i]);
            break;
        default:
            printf("Error, los valores posibles son:\n\tv - Obtener Vendedor\n\tl - Liberar Vendedor\n\td - Devolver Vendedor\n\tr - Resetear Vendedores\n\tx - Listar Vendedores\n");
            break;
    }
}

int main(int argc, char *argv[]) {
    char *host;
    char deboSeguir;

    if (argc == 1) {
        host = "LOCALHOST";
    } else if (argc == 2) {
        host = argv[1];
    } else {
        printf("Uso: %s server_host\n", argv[0]);
        exit(1);
    }

    printf("Ingrese una opcion:\n\tc - Cliente\n\tv - Vendedor\n\tf - Fin\n");
    deboSeguir = 0;
    while (deboSeguir == 0) {
        char c;
        scanf("%c", &c);

        switch (c) {
            case 'c':
                manejarClientes(host);
                break;
            case 'v':
                manejarVendedores(host);
                break;                
            case 'f':
                deboSeguir = 1;
                break;
            default:
                printf("Error, los valores posibles son:\n\tc - Cliente\n\tv - Vendedor\n\tf - Fin\n");
                break;
        }
    }
    printf("Fin\n");
    exit(0);
}

/* CLIENTE */

struct RetornoCliente numerarCliente(char *host) {
    retornoCliente *result_1;
    char *obteneridcliente_1_arg;

    CLIENT *clnt = clnt_create(host, NUMERADORCLIENTE, NUMERADORCLIENTE1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    result_1 = obteneridcliente_1((void*) &obteneridcliente_1_arg, clnt);
    if (result_1 == (retornoCliente *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    if ((*result_1).cod_ret != 1) {
        printf("Error mientras se numeraba el cliente");
    }

    clnt_destroy(clnt);

    return (*result_1).retornoCliente_u.retorno;
}

void devolverCliente(char *host, int numero) {
    void *result_2;
    int devolveridcliente_1_arg;
    CLIENT *clnt;
    
    devolveridcliente_1_arg = numero;

    clnt = clnt_create(host, NUMERADORCLIENTE, NUMERADORCLIENTE1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    result_2 = devolveridcliente_1(&devolveridcliente_1_arg, clnt);
    if (result_2 == (void *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    clnt_destroy(clnt);
}

void resetearClientes(char *host) {
    void *result_3;
    char *resetearclientes_1_arg;

    CLIENT *clnt = clnt_create(host, NUMERADORCLIENTE, NUMERADORCLIENTE1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    result_3 = resetearclientes_1((void*) &resetearclientes_1_arg, clnt);
    if (result_3 == (void *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    clnt_destroy(clnt);
}

void obtenerListadoClientes(char *host, EstadoClientes *listado) {
    retornoCliente *result_4;
    char *listadoclientes_1_arg;

    CLIENT *clnt = clnt_create(host, NUMERADORCLIENTE, NUMERADORCLIENTE1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    result_4 = listadoclientes_1((void*) &listadoclientes_1_arg, clnt);
    if (result_4 == (retornoCliente *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    if ((*result_4).cod_ret != 1) {
        printf("Error mientras se listaba los clientes");
    }

    clnt_destroy(clnt);

    memcpy(listado, (*result_4).retornoCliente_u.informacion, MAX_CLIENTES);
}

/* VENDEDOR */

int numerarVendedor(char *host) {

    retornoVendedor *result_1;
    char *obteneridvendedor_1_arg;

    CLIENT *clnt = clnt_create(host, NUMERADORVENDEDOR, NUMERADORVENDEDOR1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    result_1 = obteneridvendedor_1((void*) &obteneridvendedor_1_arg, clnt);
    if (result_1 == (retornoVendedor *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    if ((*result_1).cod_ret != 1) {
        printf("Error mientras se numeraba el vendedor");
    }

    clnt_destroy(clnt);

    return (*result_1).retornoVendedor_u.idVendedor;
}

void liberarVendedor(char *host, int numero) {
    void *result_2;
    int vendedorlibre_1_arg = numero;

    CLIENT *clnt = clnt_create(host, NUMERADORVENDEDOR, NUMERADORVENDEDOR1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    result_2 = vendedorlibre_1(&vendedorlibre_1_arg, clnt);
    if (result_2 == (void *) NULL) {
        clnt_perror(clnt, "call failed");
    }
}

void devolverVendedor(char *host, int numero) {

    void *result_3;
    int devolveridvendedor_1_arg;
    CLIENT *clnt;
    
    devolveridvendedor_1_arg = numero;

    clnt = clnt_create(host, NUMERADORVENDEDOR, NUMERADORVENDEDOR1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }


    result_3 = devolveridvendedor_1(&devolveridvendedor_1_arg, clnt);
    if (result_3 == (void *) NULL) {
        clnt_perror(clnt, "call failed");
    }


    clnt_destroy(clnt);
}

void resetearVendedores(char *host) {
    void *result_4;
    char *resetearvendedores_1_arg;


    CLIENT *clnt = clnt_create(host, NUMERADORVENDEDOR, NUMERADORVENDEDOR1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    result_4 = resetearvendedores_1((void*) &resetearvendedores_1_arg, clnt);
    if (result_4 == (void *) NULL) {
        clnt_perror(clnt, "call failed");
    }


    clnt_destroy(clnt);
}

void obtenerListadoVendedores(char *host, EstadoVendedores *listado) {
    retornoVendedor *result_5;
    char *listadovendedores_1_arg;

    CLIENT *clnt = clnt_create(host, NUMERADORVENDEDOR, NUMERADORVENDEDOR1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    result_5 = listadovendedores_1((void*) &listadovendedores_1_arg, clnt);
    if (result_5 == (retornoVendedor *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    if ((*result_5).cod_ret != 1) {
        printf("Error mientras se listaba los vendedores");
    }

    clnt_destroy(clnt);

    memcpy(listado, (*result_5).retornoVendedor_u.informacion, MAX_VENDEDORES);
}

/*
void numeradorcliente_1(char *host)
{
	CLIENT *clnt;
	retornoCliente  *result_1;
	char *obteneridcliente_1_arg;
	void  *result_2;
	int  devolveridcliente_1_arg;
	void  *result_3;
	char *resetearclientes_1_arg;
	retornoCliente  *result_4;
	char *listadoclientes_1_arg;

	clnt = clnt_create (host, NUMERADORCLIENTE, NUMERADORCLIENTE1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	result_1 = obteneridcliente_1((void*)&obteneridcliente_1_arg, clnt);
	if (result_1 == (retornoCliente *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = devolveridcliente_1(&devolveridcliente_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = resetearclientes_1((void*)&resetearclientes_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = listadoclientes_1((void*)&listadoclientes_1_arg, clnt);
	if (result_4 == (retornoCliente *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy (clnt);
}*/

/*void numeradorvendedor_1(char *host)
{
    
	CLIENT *clnt;
	retornoVendedor  *result_1;
	char *obteneridvendedor_1_arg;
	void  *result_2;
	int  vendedorlibre_1_arg;
	void  *result_3;
	int  devolveridvendedor_1_arg;
	void  *result_4;
	char *resetearvendedores_1_arg;
	retornoVendedor  *result_5;
	char *listadovendedores_1_arg;

	CLIENT *clnt = clnt_create (host, NUMERADORVENDEDOR, NUMERADORVENDEDOR1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	result_1 = obteneridvendedor_1((void*)&obteneridvendedor_1_arg, clnt);
	if (result_1 == (retornoVendedor *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = vendedorlibre_1(&vendedorlibre_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = devolveridvendedor_1(&devolveridvendedor_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = resetearvendedores_1((void*)&resetearvendedores_1_arg, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = listadovendedores_1((void*)&listadovendedores_1_arg, clnt);
	if (result_5 == (retornoVendedor *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy (clnt);
}*/