/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg_iv.h"


void
cesarprog_2(char *host, char *codcesar_2_arg)
{
	CLIENT *clnt;
	retorno  *result_1;
	//char * codcesar_2_arg;
	retorno  *result_2;
	//char * decodcesar_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CESARPROG, CESARVERS2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = codcesar_2(&codcesar_2_arg, clnt);
	if (result_1 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%s\n", (*result_1).retorno_u.message);
	char *mensajeCodificado;

	mensajeCodificado = (char *)malloc(sizeof(char)*800);
	strcpy(mensajeCodificado, (*result_1).retorno_u.message);	

	result_2 = decodcesar_2(&mensajeCodificado, clnt);
	if (result_2 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%s\n", (*result_2).retorno_u.message);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
cesarprog_3(char *host, char *codcesar_3_arg)
{
	CLIENT *clnt;
	retorno  *result_1;
	retorno  *result_2;


#ifndef	DEBUG
	clnt = clnt_create (host, CESARPROG, CESARVERS3, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = codcesar_3(&codcesar_3_arg, clnt);
	if (result_1 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%s\n", (*result_1).retorno_u.message);
	char *mensajeCodificado;

	mensajeCodificado = (char *)malloc(sizeof(char)*800);
	strcpy(mensajeCodificado, (*result_1).retorno_u.message);	

	result_2 = decodcesar_3(&mensajeCodificado, clnt);
	if (result_2 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%s\n", (*result_2).retorno_u.message);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char msg[800];
	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	strcpy(msg, argv[2]);

	cesarprog_2 (host,msg);
	cesarprog_3 (host,msg);
exit (0);
}
