/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg_iv.h"

retorno *
codcesar_2_svc(char **argp, struct svc_req *rqstp)
{

	printf("Codificando mensaje: %s\n", (*argp));
	static retorno  result;

	char *cadena = (*argp);
	char resultado[800];
	int longitud = strlen(cadena);
	int i = 0;
	for (i = 0; i < longitud; ++i) {
		if (cadena[i] == 'z') resultado[i] = 'a';
		else resultado[i] = (cadena[i] + 1); 
	}
	
	strcpy (result.retorno_u.message,resultado); /* asignacion de string segun c */
	result.cod_ret = 1;

	printf("Resultado codificacion: %s\n", resultado);

	return &result;
}

retorno *
decodcesar_2_svc(char **argp, struct svc_req *rqstp)
{

	printf("Decodificando mensaje: %s\n", (*argp));
	static retorno  result;

	
	char *cadena = (*argp);
	char resultado[800];
	int longitud = strlen(cadena);
	int i = 0;
	for (i = 0; i < longitud; ++i) {
		if (cadena[i] == 'a') resultado[i] = 'z';
		else resultado[i] = (cadena[i] - 1); 
	}
	
	strcpy (result.retorno_u.message,resultado); /* asignacion de string segun c */
	result.cod_ret = 1;
	printf("Resultado decodificacion: %s\n", resultado);
	return &result;
}

retorno *
codcesar_3_svc(char **argp, struct svc_req *rqstp)
{

	printf("Codificando mensaje: %s\n", (*argp));
	static retorno  result;

	char *cadena = (*argp);
	char resultado[800];
	int longitud = strlen(cadena);
	int i = 0;
	for (i = 0; i < longitud; ++i) {
		if (cadena[i] == 'z') resultado[i] = 'b';
		else if (cadena[i] == 'y') resultado[i] = 'a';
		else resultado[i] = (cadena[i] + 2); 
	}
	
	strcpy (result.retorno_u.message,resultado); /* asignacion de string segun c */
	result.cod_ret = 1;

	printf("Resultado codificacion: %s\n", resultado);

	return &result;
}

retorno *
decodcesar_3_svc(char **argp, struct svc_req *rqstp)
{

	printf("Decodificando mensaje: %s\n", (*argp));
	static retorno  result;

	
	char *cadena = (*argp);
	char resultado[800];
	int longitud = strlen(cadena);
	int i = 0;
	for (i = 0; i < longitud; ++i) {
		if (cadena[i] == 'a') resultado[i] = 'y';
		else if (cadena[i] == 'b') resultado[i] = 'z';
		else resultado[i] = (cadena[i] - 2); 
	}
	
	strcpy (result.retorno_u.message,resultado); /* asignacion de string segun c */
	result.cod_ret = 1;
	printf("Resultado decodificacion: %s\n", resultado);
	return &result;
}

